### ISSUE TITLE
Can't set configs on Windows

### ISSUE THREAD

**Issue by leochras** [studiorack/studiorack-cli#3]
I can't set the pluginFolder path and also, when I change it in the app it doesn't reflect the change in the cli. This could be a windows specific issue tho.

![image](https://user-images.githubusercontent.com/16163571/166483805-c52cf770-73df-4531-95fe-8b3305f9c4b3.png)

![image](https://user-images.githubusercontent.com/16163571/166483319-f3fef7c4-44fc-45f3-a037-b91ae717c5db.png)

edit: also doesn't work without "" or with /

**Comment by leochras** [comment]
Setting other properties, like `projectFolder `also doesn't work.

**Comment by kmturley** [comment]
Which version of the cli are your using?
```
studiorack --version
```

It might be that you are running an old version. It's working for me!
![Screenshot 2022-05-06 161154](https://user-images.githubusercontent.com/1710493/167226827-5496e43b-94f3-452a-8af6-d8bb181eea9b.png)

**Comment by kmturley** [comment]
This commit will automatically update the StudioRack cli if it detects that it is out-of-date:
https://github.com/studiorack/studiorack-core/commit/105f31fc5ded50662a663b936892c25360f6ee0c

Will test this in a new release soon

**Comment by leochras** [comment]
I was on version `1.1.12` and upgraded. to 1.1.15. I can now set the configs in the cli, but the change is not reflected in the GUI.

**Comment by kmturley** [comment]
This should be fixed in the latest release. Update using:
`npm install @studiorack/cli@latest`

**Comment by leochras** [comment]
But the issue itself seems to be fixes, nice work!

**Comment by kmturley** [comment]
Nesting the CLI tool inside the App was a bad idea of mine. It was causing all sorts of issues:
- Versions were different
- User could install a different version while the App was open
- App upgrading the CLI would change it for the entire computer
- Could not run different versions of the App on the same computer
- App and CLI could run different versions of the core library which would cause bugs

I reverted to my original approach where there is a mini CLI type script which can be run as part of the core library.

This decouples the App and the CLI tool, and ensures the core library code is shared.

So CLI tool is not used at all by the App. You can uninstall and the App will still function
